version: "3.9"

networks:
  mynetwork:
    driver: bridge

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}"    
    networks:
      - mynetwork

  client:
    build: ./src/Web/ClientApp/mobile-monitoring
    ports:
      - "4200:80"
    depends_on:
      - web
    networks:
      - mynetwork


